### ISSUE TITLE
Github callback code

### ISSUE THREAD

**Issue by iamShantanu101** [vinitkumar/node-twitter#82] opened 2016-05-07 18:30 UTC
Giving a github callback code in some hash when tried to run this app by modifying the config/config.json file and adding appropriate clientID and clientSecret.
For testing purpose you can try once : https://fathomless-gorge-17505.herokuapp.com/login

**Comment by vinitkumar** [comment] 2016-05-07 19:01
@iamShantanu101 I think the issue is with your application configuration on Github. Try and change the callback url to https://fathomless-gorge-17505.herokuapp.com like how I did it for my app. 

![screen shot 2016-05-08 at 12 30 05 am](https://cloud.githubusercontent.com/assets/537678/15093963/2e2b6b9e-14b4-11e6-9176-0518e3d09d05.png)

Let me know if this solves your issue.

**Comment by iamShantanu101** [comment] 2016-05-08 05:57
Thanks! It works now. I was writing oauth2 in place of auth.

**Comment by vinitkumar** [comment] 2016-05-08 15:51
Cool. Closing this issue. Reopen or create a new one if you have another issue.

**Closed by vinitkumar** 2016-05-08 15:51 UTC
Labels: 3 - Done

**Comment by vinitkumar** [comment] 2016-05-10 09:26
@iamShantanu101 I just checked your project on heroku. Here are couple of things I suggest you change/update.

- Please don't use the same database URL as you will likely consume the my database plan. So please change that.
- Also, when you fork anyones project and deploy yourself try and not remove the attribution to the original author. Even if you want to add your name, try and append not replace. 

I know you don't have much experience in all these things and you probably didn't do it knowingly. 

Thanks!

**Comment by iamShantanu101** [comment] 2016-05-10 12:48
Thanks for pointing out these things. I wasn't aware of them. However I'd like to contribute to any future node.js project.

Cheers!

**Comment by vinitkumar** [comment] 2016-05-10 17:08
@iamShantanu101 Great. Will let you know if I start a new project. In the meanwhile, Keep Hacking.

May the force be with you 👍
